### ISSUE TITLE
error in x (and error in y)

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/global_bird_abundance#1]
Need to model the error in x. That @itchyshin is working on.

I was wrong about what ```sd_of_abund``` was quantifying.

It actually is quantifying this that Shinichi did a long time ago:

```
ln_sd_of_abund = log10(sd(mean_of_abundance)) + 1/(2*(count_sd - 1)), # sd (time x space) of estaimtes of mean estiamtes with small sample size corrections (small sample size tend to underestiamte SD)
            sd_of_abund = exp(ln_sd_of_abund))
```

So it is calculating the error (sd) in the number of different mean abundance (eBird relaitve abundance) measures for each species (based on region/month calculations)...

This script is where this is calculated: https://github.com/coreytcallaghan/global_bird_abundance/blob/master/R/Cleaning%20data%20files/prepare_file_for_detectability_modelling.R

So I think se should be equal to ```sd_of_abund/sqrt(count_sd)``` after reading in the ```mod_df``` dataframe using this script: https://github.com/coreytcallaghan/global_bird_abundance/blob/master/R/detectability_modelling.R

Does that make sense? 

Error in y we will use weights in the model and show that it is less error, so we take an inclusive approach and are conservative in our error propagation.

**Comment by itchyshin** [comment]
@coreytcallaghan - thanks!

Will work on this - I may not get to this till the weekend as I need a fairly big chunk of time to get a measurement error model working (https://mc-stan.org/docs/2_18/stan-users-guide/bayesian-measurement-error-model.html).

**Comment by coreytcallaghan** [comment]
No worries. Message on WhatsApp if you have any questions and I can try to help. Thanks @itchyshin!

**Comment by itchyshin** [comment]
OK - I am working on this now

```
ln_sd_of_abund = log10(sd(mean_of_abundance)) + 1/(2*(count_sd - 1)), # sd (time x space) of estaimtes of mean estiamtes with small sample size corrections (small sample size tend to underestiamte SD)
            sd_of_abund = exp(ln_sd_of_abund))
```

is not quite right - we should use log rather than log10 - otherwise, exp won't work. Also, this is SD rather than SE - we can get SE

```
ln_sd_of_abund = log(sd(mean_of_abundance)) + 1/(2*(count_sd - 1)), # sd (time x space) of estaimtes of mean estiamtes with small sample size corrections (small sample size tend to underestiamte SD)
            sd_of_abund = exp(ln_sd_of_abund))

abundance_SD_log10 = (sd_of_abund/sqrt(count_sd))/(log(10)*mean_of_abund))
```

Anyway, we can get now this in log10 scale and then we are ready and also this is SD of the sample so I turned this SD into SE (dividing by sqrt(count_sd) (SD of the estimate)

**Comment by itchyshin** [comment]
OK @coreytcallaghan in brms- I got the model working now - needs some time to get the same posterior out - it now more looks like a Type II slope estimate

**Comment by itchyshin** [comment]
Also, I will do the model (using MCMCglmm) with and without errors in Y - and compare errors between these two models. We should be able to show ones without SD (errors) will have higher errors (this is our original model) - probably I will do this early next week (I have other things to do today)

**Comment by itchyshin** [comment]
@coreytcallaghan and @wcornwell - I think I did it - I still probably need to run the brms model longer (as it is complaining that chains have not mixed well). But here are comparisons of MCMCglmm (type I) and brms (type II) - you can see brms has slopes (and intercepts) bigger than those of MCMCglmm (closer to 1) but other things look pretty similar (give me a few more days to finish off this issue). 

![MCMC_histograms](https://user-images.githubusercontent.com/12078523/104830251-31180900-58d1-11eb-952c-b1d6d2ae5d85.png)
![brms_histograms](https://user-images.githubusercontent.com/12078523/104830255-35442680-58d1-11eb-94a2-717a1daf31d5.png)

**Comment by itchyshin** [comment]
@coreytcallaghan - I had more time today - all is done

You will find a new file "detectability_modelling2.R" in the R folder.
 
I could not upload the models as they were too big - but you can run MCMCglmm models easily. Anyway, anything you want me to do let me know. 

I am happy to write replies to the related comments.

**Comment by coreytcallaghan** [comment]
Awesome! Thanks @itchyshin! Sorry - wasn't checking emails this weekend.

So, are we going to stick with the original MCMCglmm model then in our framework? And the point here is to show that the errors are greater in brms than in MCMCglmm?

**Comment by itchyshin** [comment]
No no we use both models to address Ref 1's comments: @coreytcallaghan 

I am using MCMCglmm to show you do not need to incorporate SD in Y (the first tick)
And then I am using brms for the model we use - I already saved new slopes and intercepts with errors (we will use these new estimates) = the second tick

**Comment by itchyshin** [comment]
@coreytcallaghan - I am happy to chat on Skype or Zoom if this will sort things quicker? (although I am going home now) - maybe tomorrow morning for me (and your evening)?

**Comment by coreytcallaghan** [comment]
Okay - sorry! Thought that was the case. Just wanted to make sure! :)

**Comment by coreytcallaghan** [comment]
Yup - give me a day to play around and I'll let you know if we should catch up one morning this week!
